# Generated by Django 4.1 on 2022-08-22 07:43

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.UserManager()),
            ],
        ),
    ]
